package com.app.jetpackmoviecatalogue.utils;

import com.app.jetpackmoviecatalogue.data.source.local.entity.Content;
import com.app.jetpackmoviecatalogue.data.source.remote.response.ContentResponse;

import java.util.ArrayList;
import java.util.List;

public class FakeDataDummy {
    public static List<Content> generateDummyMovies() {
        List<Content> contents = new ArrayList<>();
        Content con290859 = new Content("Terminator: Dark Fate", "2019-11-01", "More than two decades have passed since Sarah Connor prevented Judgment Day, changed the future, and re-wrote the fate of the human race. Dani Ramos is living a simple life in Mexico City with her brother and father when a highly advanced and deadly new Terminator – a Rev-9 – travels back through time to hunt and kill her. Dani's survival depends on her joining forces with two warriors: Grace, an enhanced super-soldier from the future, and a battle-hardened Sarah Connor. As the Rev-9 ruthlessly destroys everything and everyone in its path on the hunt for Dani, the three are led to a T-800 from Sarah’s past that may be their last best hope.", "290859", "/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg", "/a6cDxdwaQIFjSkXf7uskg78ZyTq.jpg", 6.5f, " movie");
        ArrayList<Integer> genreIds290859 = new ArrayList<>();
        contents.add(con290859);
        genreIds290859.add(28);
        genreIds290859.add(878);
        con290859.setGenreIds(genreIds290859);
        Content con338967 = new Content("Zombieland: Double Tap", "2019-10-18", "The group will face a new zombie threat as a new breed of zombie has developed. This new super-zombie type is faster, bigger, and stronger than the previous strain of zombies and harder to kill. These super-zombies have started grouping up into a horde going from city to city leaving a path of destruction behind them.", "338967", "/pIcV8XXIIvJCbtPoxF9qHMKdRr2.jpg", "/jCCdt0e8Xe9ttvevD4S3TSMNdH.jpg", 7.5f, " movie");
        ArrayList<Integer> genreIds338967 = new ArrayList<>();
        contents.add(con338967);
        genreIds338967.add(28);
        genreIds338967.add(35);
        genreIds338967.add(27);
        con338967.setGenreIds(genreIds338967);
        Content con568012 = new Content("One Piece: Stampede", "2019-10-24", "One Piece: Stampede is a stand-alone film that celebrates the anime's 20th Anniversary and takes place outside the canon of the \"One Piece\" TV series. Monkey D. Luffy and his Straw Hat pirate crew are invited to a massive Pirate Festival that brings many of the most iconic characters from throughout the franchise to participate in competition with the Straw Hats to find Roger's treasure. It also pits the Straw Hats against a new enemy named Bullet, a former member of Roger's crew.", "568012", "/4E2lyUGLEr3yH4q6kJxPkQUhX7n.jpg", "/iGnCzXEx0cFlUbpyAMeHwHWhPhx.jpg", 7.6f, " movie");
        ArrayList<Integer> genreIds568012 = new ArrayList<>();
        contents.add(con568012);
        genreIds568012.add(28);
        genreIds568012.add(12);
        genreIds568012.add(16);
        con568012.setGenreIds(genreIds568012);
        Content con481084 = new Content("The Addams Family", "2019-10-11", "The Addams family's lives begin to unravel when they face-off against a treacherous, greedy crafty reality-TV host while also preparing for their extended family to arrive for a major celebration.", "481084", "/uaXNjRkDdjfxfVuKHo25wkA6CiA.jpg", "/xS89uFXPKKwyWJgM7ljAmuAtDMh.jpg", 5.9f, " movie");
        ArrayList<Integer> genreIds481084 = new ArrayList<>();
        contents.add(con481084);
        genreIds481084.add(16);
        genreIds481084.add(35);
        genreIds481084.add(14);
        genreIds481084.add(10751);
        con481084.setGenreIds(genreIds481084);
        Content con578189 = new Content("Black and Blue", "2019-10-25", "Exposure follows a rookie Detroit African-American female cop who stumbles upon corrupt officers who are murdering a drug dealer, an incident captured by her body cam. They pursue her through the night in an attempt to destroy the footage, but to make matters worse, they've tipped off a criminal gang that she's responsible for the dealer's death.", "578189", "/fjmMu9fpqMMF17mCyLhNfkagKB0.jpg", "/zBAoNL50oFRCAJvEEQEKD8M48pV.jpg", 5.2f, " movie");
        ArrayList<Integer> genreIds578189 = new ArrayList<>();
        contents.add(con578189);
        genreIds578189.add(28);
        genreIds578189.add(80);
        genreIds578189.add(18);
        con578189.setGenreIds(genreIds578189);
        Content con511987 = new Content("Crawl", "2019-07-12", "When a huge hurricane hits her hometown in Florida, Haley ignores evacuation orders to look for her father. After finding him badly wounded, both are trapped by the flood. With virtually no time to escape the storm, they discover that rising water levels are the least of their problems.", "511987", "/9kOtMOUa5HrOiIG2Z9Anv7M8AbY.jpg", "/lm4xH0YwFbVvTgdtau1thNK5S6J.jpg", 6.1f, " movie");
        ArrayList<Integer> genreIds511987 = new ArrayList<>();
        contents.add(con511987);
        genreIds511987.add(28);
        genreIds511987.add(18);
        genreIds511987.add(27);
        genreIds511987.add(53);
        con511987.setGenreIds(genreIds511987);
        Content con496243 = new Content("Parasite", "2019-10-11", "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", "496243", "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", 8.5f, " movie");
        ArrayList<Integer> genreIds496243 = new ArrayList<>();
        contents.add(con496243);
        genreIds496243.add(35);
        genreIds496243.add(18);
        genreIds496243.add(53);
        con496243.setGenreIds(genreIds496243);
        Content con501170 = new Content("Doctor Sleep", "2019-11-08", "A traumatized, alcoholic Dan Torrance meets Abra, a kid who also has the ability to \"shine.\" He tries to protect her from the True Knot, a cult who's goal is to feed off people like them in order to remain immortal.", "501170", "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg", "/4D4Ic9N4tnwaW4x241LGb1XOi7O.jpg", 6.9f, " movie");
        ArrayList<Integer> genreIds501170 = new ArrayList<>();
        contents.add(con501170);
        genreIds501170.add(27);
        con501170.setGenreIds(genreIds501170);
        Content con599975 = new Content("Countdown", "2019-10-25", "A young nurse downloads an app that tells her she only has three days to live. With time ticking away and a mysterious figure haunting her, she must find a way to save her life before time runs out.", "599975", "/qCDPKUMX5xrxxQY8XhGVCKO3fks.jpg", "/hzL2P0tcU62A6JHPhprI8ZyBI73.jpg", 6.0f, " movie");
        ArrayList<Integer> genreIds599975 = new ArrayList<>();
        contents.add(con599975);
        genreIds599975.add(27);
        genreIds599975.add(53);
        con599975.setGenreIds(genreIds599975);
        Content con540901 = new Content("Hustlers", "2019-09-13", "A crew of savvy former strip club employees band together to turn the tables on their Wall Street clients.", "540901", "/zBhv8rsLOfpFW2M5b6wW78Uoojs.jpg", "/jTab4cf4X1dJJVS4F8UOGuesvPd.jpg", 6.1f, " movie");
        ArrayList<Integer> genreIds540901 = new ArrayList<>();
        contents.add(con540901);
        genreIds540901.add(35);
        genreIds540901.add(80);
        genreIds540901.add(18);
        con540901.setGenreIds(genreIds540901);
        Content con431580 = new Content("Abominable", "2019-09-27", "A group of misfits encounter a young Yeti named Everest, and they set off to reunite the magical creature with his family on the mountain of his namesake.", "431580", "/llhj3xtNes2Ri4d9HqtleKo1CfL.jpg", "/tLCDKsXo6D84IVFanoElosSEKdp.jpg", 6.9f, " movie");
        ArrayList<Integer> genreIds431580 = new ArrayList<>();
        contents.add(con431580);
        genreIds431580.add(12);
        genreIds431580.add(16);
        genreIds431580.add(35);
        genreIds431580.add(10751);
        con431580.setGenreIds(genreIds431580);
        Content con522924 = new Content("The Art of Racing in the Rain", "2019-08-09", "Enzo, a family dog with a near-human soul and a philosopher's mind, evaluates his life through the lessons learned by his human owner, the race-car driver Denny Swift.", "522924", "/mi5VN4ww0JZgRFJIaPxxTGKjUg7.jpg", "/6esNUoXh4xQvucB7o7e3TCfjI65.jpg", 8.1f, " movie");
        ArrayList<Integer> genreIds522924 = new ArrayList<>();
        contents.add(con522924);
        genreIds522924.add(35);
        genreIds522924.add(18);
        genreIds522924.add(10749);
        con522924.setGenreIds(genreIds522924);
        Content con503919 = new Content("The Lighthouse", "2019-10-18", "The hypnotic and hallucinatory tale of two lighthouse keepers on a remote and mysterious New England island in the 1890s.", "503919", "/3nk9UoepYmv1G9oP18q6JJCeYwN.jpg", "/qlYhhBUseMUawwbvHCdPLXvBELv.jpg", 8.2f, " movie");
        ArrayList<Integer> genreIds503919 = new ArrayList<>();
        contents.add(con503919);
        genreIds503919.add(18);
        genreIds503919.add(14);
        genreIds503919.add(27);
        con503919.setGenreIds(genreIds503919);
        Content con398978 = new Content("The Irishman", "2019-11-01", "World War II veteran and mob hitman Frank \"The Irishman\" Sheeran recalls his possible involvement with the slaying of union leader Jimmy Hoffa.", "398978", "/eXH2w0Ylh706Rwj6CHFm1FKRBXG.jpg", "/aZ1ZqJ4uO1RK5gU5jRsO4qG7rJo.jpg", 8.8f, " movie");
        ArrayList<Integer> genreIds398978 = new ArrayList<>();
        contents.add(con398978);
        genreIds398978.add(80);
        genreIds398978.add(18);
        con398978.setGenreIds(genreIds398978);
        Content con330457 = new Content("Frozen II", "2019-11-22", "Elsa, Anna, Kristoff and Olaf are going far in the forest to know the truth about an ancient mystery of their kingdom.", "330457", "/zHQFqG0e5p9Fwhv5v6XIP9fLtYk.jpg", "/qxSi1e8ht92grVUoApGfz9oCvJv.jpg", 0.0f, " movie");
        ArrayList<Integer> genreIds330457 = new ArrayList<>();
        contents.add(con330457);
        genreIds330457.add(12);
        genreIds330457.add(16);
        genreIds330457.add(35);
        genreIds330457.add(14);
        genreIds330457.add(10402);
        genreIds330457.add(10751);
        con330457.setGenreIds(genreIds330457);
        Content con423204 = new Content("Angel Has Fallen", "2019-08-23", "After the events in the previous film, Secret Service agent Mike Banning finds himself framed for an assassination attempt on the President. Pursued by his own agency and the FBI, Banning races to clear his name and uncover the real terrorist threat which has set its sights on Air Force One.", "423204", "/fapXd3v9qTcNBTm39ZC4KUVQDNf.jpg", "/k2WyDw2NTUIWnuEs5gT7wgrCQg6.jpg", 5.7f, " movie");
        ArrayList<Integer> genreIds423204 = new ArrayList<>();
        contents.add(con423204);
        genreIds423204.add(28);
        con423204.setGenreIds(genreIds423204);
        Content con535544 = new Content("Downton Abbey", "2019-09-20", "The beloved Crawleys and their intrepid staff prepare for the most important moment of their lives. A royal visit from the King and Queen of England will unleash scandal, romance and intrigue that will leave the future of Downton hanging in the balance.", "535544", "/pWt1iRuhNpeVDNP2QiUT2C5OiBt.jpg", "/dixk6fO4P71WJsJgbdzLHEUpJgA.jpg", 7.2f, " movie");
        ArrayList<Integer> genreIds535544 = new ArrayList<>();
        contents.add(con535544);
        genreIds535544.add(18);
        con535544.setGenreIds(genreIds535544);
        Content con416153 = new Content("Arctic Dogs", "2019-11-01", "Animals band together to save the day when the evil Otto Von Walrus hatches a sinister scheme to accelerate global warming and melt the Arctic Circle.", "416153", "/gS95M2jMS29zTyc9Aq7Vxx6eXPZ.jpg", "/uTfdOozort4sp9kukWxEmdmRsqJ.jpg", 0.0f, " movie");
        ArrayList<Integer> genreIds416153 = new ArrayList<>();
        contents.add(con416153);
        genreIds416153.add(16);
        con416153.setGenreIds(genreIds416153);
        Content con604165 = new Content("Kamen Rider Zi-O the Movie: Over Quartzer!", "2019-07-26", "The Quartzers, calling themselves the Wardens of Time, appear after Sougo Tokiwa has collected all of the Heisei Era Ride Watches. A grand conspiracy behind the birth of the King of Time becomes ever clearer...", "604165", "/ftVSHLDbkVh0XycxGPqszEUyt3T.jpg", "/3yb93vHjVc9amUgLhAHRJGMNGpH.jpg", 7.4f, " movie");
        ArrayList<Integer> genreIds604165 = new ArrayList<>();
        contents.add(con604165);
        genreIds604165.add(28);
        genreIds604165.add(12);
        genreIds604165.add(878);
        con604165.setGenreIds(genreIds604165);
        Content con505600 = new Content("Booksmart", "2019-05-24", "Two academic teenage superstars realize, on the eve of their high school graduation, that they should have worked less and played more. Determined to never fall short of their peers, the girls set out on a mission to cram four years of fun into one night.", "505600", "/2aSxRDmisJP90H3S0aocyuQIe4z.jpg", "/wcAqndL2MkIjPrCrYeuE794weNE.jpg", 7.2f, " movie");
        ArrayList<Integer> genreIds505600 = new ArrayList<>();
        contents.add(con505600);
        genreIds505600.add(35);
        genreIds505600.add(18);
        con505600.setGenreIds(genreIds505600);


        return contents;
    }

    public static List<ContentResponse> generateRemoteDummyMovies() {
        List<ContentResponse> contents = new ArrayList<>();
        ContentResponse res290859 = new ContentResponse("Terminator: Dark Fate", "2019-11-01", "More than two decades have passed since Sarah Connor prevented Judgment Day, changed the future, and re-wrote the fate of the human race. Dani Ramos is living a simple life in Mexico City with her brother and father when a highly advanced and deadly new Terminator – a Rev-9 – travels back through time to hunt and kill her. Dani's survival depends on her joining forces with two warriors: Grace, an enhanced super-soldier from the future, and a battle-hardened Sarah Connor. As the Rev-9 ruthlessly destroys everything and everyone in its path on the hunt for Dani, the three are led to a T-800 from Sarah’s past that may be their last best hope.", "290859", "/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg", "/a6cDxdwaQIFjSkXf7uskg78ZyTq.jpg", 6.5f, " movie");
        List<Integer> genreIds290859 = new ArrayList<>();
        contents.add(res290859);
        genreIds290859.add(28);
        genreIds290859.add(878);
        res290859.setGenreIds(genreIds290859);
        ContentResponse res338967 = new ContentResponse("Zombieland: Double Tap", "2019-10-18", "The group will face a new zombie threat as a new breed of zombie has developed. This new super-zombie type is faster, bigger, and stronger than the previous strain of zombies and harder to kill. These super-zombies have started grouping up into a horde going from city to city leaving a path of destruction behind them.", "338967", "/pIcV8XXIIvJCbtPoxF9qHMKdRr2.jpg", "/jCCdt0e8Xe9ttvevD4S3TSMNdH.jpg", 7.5f, " movie");
        List<Integer> genreIds338967 = new ArrayList<>();
        contents.add(res338967);
        genreIds338967.add(28);
        genreIds338967.add(35);
        genreIds338967.add(27);
        res338967.setGenreIds(genreIds338967);
        ContentResponse res568012 = new ContentResponse("One Piece: Stampede", "2019-10-24", "One Piece: Stampede is a stand-alone film that celebrates the anime's 20th Anniversary and takes place outside the canon of the \"One Piece\" TV series. Monkey D. Luffy and his Straw Hat pirate crew are invited to a massive Pirate Festival that brings many of the most iconic characters from throughout the franchise to participate in competition with the Straw Hats to find Roger's treasure. It also pits the Straw Hats against a new enemy named Bullet, a former member of Roger's crew.", "568012", "/4E2lyUGLEr3yH4q6kJxPkQUhX7n.jpg", "/iGnCzXEx0cFlUbpyAMeHwHWhPhx.jpg", 7.6f, " movie");
        List<Integer> genreIds568012 = new ArrayList<>();
        contents.add(res568012);
        genreIds568012.add(28);
        genreIds568012.add(12);
        genreIds568012.add(16);
        res568012.setGenreIds(genreIds568012);
        ContentResponse res481084 = new ContentResponse("The Addams Family", "2019-10-11", "The Addams family's lives begin to unravel when they face-off against a treacherous, greedy crafty reality-TV host while also preparing for their extended family to arrive for a major celebration.", "481084", "/uaXNjRkDdjfxfVuKHo25wkA6CiA.jpg", "/xS89uFXPKKwyWJgM7ljAmuAtDMh.jpg", 5.9f, " movie");
        List<Integer> genreIds481084 = new ArrayList<>();
        contents.add(res481084);
        genreIds481084.add(16);
        genreIds481084.add(35);
        genreIds481084.add(14);
        genreIds481084.add(10751);
        res481084.setGenreIds(genreIds481084);
        ContentResponse res578189 = new ContentResponse("Black and Blue", "2019-10-25", "Exposure follows a rookie Detroit African-American female cop who stumbles upon corrupt officers who are murdering a drug dealer, an incident captured by her body cam. They pursue her through the night in an attempt to destroy the footage, but to make matters worse, they've tipped off a criminal gang that she's responsible for the dealer's death.", "578189", "/fjmMu9fpqMMF17mCyLhNfkagKB0.jpg", "/zBAoNL50oFRCAJvEEQEKD8M48pV.jpg", 5.2f, " movie");
        List<Integer> genreIds578189 = new ArrayList<>();
        contents.add(res578189);
        genreIds578189.add(28);
        genreIds578189.add(80);
        genreIds578189.add(18);
        res578189.setGenreIds(genreIds578189);
        ContentResponse res511987 = new ContentResponse("Crawl", "2019-07-12", "When a huge hurricane hits her hometown in Florida, Haley ignores evacuation orders to look for her father. After finding him badly wounded, both are trapped by the flood. With virtually no time to escape the storm, they discover that rising water levels are the least of their problems.", "511987", "/9kOtMOUa5HrOiIG2Z9Anv7M8AbY.jpg", "/lm4xH0YwFbVvTgdtau1thNK5S6J.jpg", 6.1f, " movie");
        List<Integer> genreIds511987 = new ArrayList<>();
        contents.add(res511987);
        genreIds511987.add(28);
        genreIds511987.add(18);
        genreIds511987.add(27);
        genreIds511987.add(53);
        res511987.setGenreIds(genreIds511987);
        ContentResponse res496243 = new ContentResponse("Parasite", "2019-10-11", "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", "496243", "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", 8.5f, " movie");
        List<Integer> genreIds496243 = new ArrayList<>();
        contents.add(res496243);
        genreIds496243.add(35);
        genreIds496243.add(18);
        genreIds496243.add(53);
        res496243.setGenreIds(genreIds496243);
        ContentResponse res501170 = new ContentResponse("Doctor Sleep", "2019-11-08", "A traumatized, alcoholic Dan Torrance meets Abra, a kid who also has the ability to \"shine.\" He tries to protect her from the True Knot, a cult who's goal is to feed off people like them in order to remain immortal.", "501170", "/p69QzIBbN06aTYqRRiCOY1emNBh.jpg", "/4D4Ic9N4tnwaW4x241LGb1XOi7O.jpg", 6.9f, " movie");
        List<Integer> genreIds501170 = new ArrayList<>();
        contents.add(res501170);
        genreIds501170.add(27);
        res501170.setGenreIds(genreIds501170);
        ContentResponse res599975 = new ContentResponse("Countdown", "2019-10-25", "A young nurse downloads an app that tells her she only has three days to live. With time ticking away and a mysterious figure haunting her, she must find a way to save her life before time runs out.", "599975", "/qCDPKUMX5xrxxQY8XhGVCKO3fks.jpg", "/hzL2P0tcU62A6JHPhprI8ZyBI73.jpg", 6.0f, " movie");
        List<Integer> genreIds599975 = new ArrayList<>();
        contents.add(res599975);
        genreIds599975.add(27);
        genreIds599975.add(53);
        res599975.setGenreIds(genreIds599975);
        ContentResponse res540901 = new ContentResponse("Hustlers", "2019-09-13", "A crew of savvy former strip club employees band together to turn the tables on their Wall Street clients.", "540901", "/zBhv8rsLOfpFW2M5b6wW78Uoojs.jpg", "/jTab4cf4X1dJJVS4F8UOGuesvPd.jpg", 6.1f, " movie");
        List<Integer> genreIds540901 = new ArrayList<>();
        contents.add(res540901);
        genreIds540901.add(35);
        genreIds540901.add(80);
        genreIds540901.add(18);
        res540901.setGenreIds(genreIds540901);
        ContentResponse res431580 = new ContentResponse("Abominable", "2019-09-27", "A group of misfits encounter a young Yeti named Everest, and they set off to reunite the magical creature with his family on the mountain of his namesake.", "431580", "/llhj3xtNes2Ri4d9HqtleKo1CfL.jpg", "/tLCDKsXo6D84IVFanoElosSEKdp.jpg", 6.9f, " movie");
        List<Integer> genreIds431580 = new ArrayList<>();
        contents.add(res431580);
        genreIds431580.add(12);
        genreIds431580.add(16);
        genreIds431580.add(35);
        genreIds431580.add(10751);
        res431580.setGenreIds(genreIds431580);
        ContentResponse res522924 = new ContentResponse("The Art of Racing in the Rain", "2019-08-09", "Enzo, a family dog with a near-human soul and a philosopher's mind, evaluates his life through the lessons learned by his human owner, the race-car driver Denny Swift.", "522924", "/mi5VN4ww0JZgRFJIaPxxTGKjUg7.jpg", "/6esNUoXh4xQvucB7o7e3TCfjI65.jpg", 8.1f, " movie");
        List<Integer> genreIds522924 = new ArrayList<>();
        contents.add(res522924);
        genreIds522924.add(35);
        genreIds522924.add(18);
        genreIds522924.add(10749);
        res522924.setGenreIds(genreIds522924);
        ContentResponse res503919 = new ContentResponse("The Lighthouse", "2019-10-18", "The hypnotic and hallucinatory tale of two lighthouse keepers on a remote and mysterious New England island in the 1890s.", "503919", "/3nk9UoepYmv1G9oP18q6JJCeYwN.jpg", "/qlYhhBUseMUawwbvHCdPLXvBELv.jpg", 8.2f, " movie");
        List<Integer> genreIds503919 = new ArrayList<>();
        contents.add(res503919);
        genreIds503919.add(18);
        genreIds503919.add(14);
        genreIds503919.add(27);
        res503919.setGenreIds(genreIds503919);
        ContentResponse res398978 = new ContentResponse("The Irishman", "2019-11-01", "World War II veteran and mob hitman Frank \"The Irishman\" Sheeran recalls his possible involvement with the slaying of union leader Jimmy Hoffa.", "398978", "/eXH2w0Ylh706Rwj6CHFm1FKRBXG.jpg", "/aZ1ZqJ4uO1RK5gU5jRsO4qG7rJo.jpg", 8.8f, " movie");
        List<Integer> genreIds398978 = new ArrayList<>();
        contents.add(res398978);
        genreIds398978.add(80);
        genreIds398978.add(18);
        res398978.setGenreIds(genreIds398978);
        ContentResponse res330457 = new ContentResponse("Frozen II", "2019-11-22", "Elsa, Anna, Kristoff and Olaf are going far in the forest to know the truth about an ancient mystery of their kingdom.", "330457", "/zHQFqG0e5p9Fwhv5v6XIP9fLtYk.jpg", "/qxSi1e8ht92grVUoApGfz9oCvJv.jpg", 0.0f, " movie");
        List<Integer> genreIds330457 = new ArrayList<>();
        contents.add(res330457);
        genreIds330457.add(12);
        genreIds330457.add(16);
        genreIds330457.add(35);
        genreIds330457.add(14);
        genreIds330457.add(10402);
        genreIds330457.add(10751);
        res330457.setGenreIds(genreIds330457);
        ContentResponse res423204 = new ContentResponse("Angel Has Fallen", "2019-08-23", "After the events in the previous film, Secret Service agent Mike Banning finds himself framed for an assassination attempt on the President. Pursued by his own agency and the FBI, Banning races to clear his name and uncover the real terrorist threat which has set its sights on Air Force One.", "423204", "/fapXd3v9qTcNBTm39ZC4KUVQDNf.jpg", "/k2WyDw2NTUIWnuEs5gT7wgrCQg6.jpg", 5.7f, " movie");
        List<Integer> genreIds423204 = new ArrayList<>();
        contents.add(res423204);
        genreIds423204.add(28);
        res423204.setGenreIds(genreIds423204);
        ContentResponse res535544 = new ContentResponse("Downton Abbey", "2019-09-20", "The beloved Crawleys and their intrepid staff prepare for the most important moment of their lives. A royal visit from the King and Queen of England will unleash scandal, romance and intrigue that will leave the future of Downton hanging in the balance.", "535544", "/pWt1iRuhNpeVDNP2QiUT2C5OiBt.jpg", "/dixk6fO4P71WJsJgbdzLHEUpJgA.jpg", 7.2f, " movie");
        List<Integer> genreIds535544 = new ArrayList<>();
        contents.add(res535544);
        genreIds535544.add(18);
        res535544.setGenreIds(genreIds535544);
        ContentResponse res416153 = new ContentResponse("Arctic Dogs", "2019-11-01", "Animals band together to save the day when the evil Otto Von Walrus hatches a sinister scheme to accelerate global warming and melt the Arctic Circle.", "416153", "/gS95M2jMS29zTyc9Aq7Vxx6eXPZ.jpg", "/uTfdOozort4sp9kukWxEmdmRsqJ.jpg", 0.0f, " movie");
        List<Integer> genreIds416153 = new ArrayList<>();
        contents.add(res416153);
        genreIds416153.add(16);
        res416153.setGenreIds(genreIds416153);
        ContentResponse res604165 = new ContentResponse("Kamen Rider Zi-O the Movie: Over Quartzer!", "2019-07-26", "The Quartzers, calling themselves the Wardens of Time, appear after Sougo Tokiwa has collected all of the Heisei Era Ride Watches. A grand conspiracy behind the birth of the King of Time becomes ever clearer...", "604165", "/ftVSHLDbkVh0XycxGPqszEUyt3T.jpg", "/3yb93vHjVc9amUgLhAHRJGMNGpH.jpg", 7.4f, " movie");
        List<Integer> genreIds604165 = new ArrayList<>();
        contents.add(res604165);
        genreIds604165.add(28);
        genreIds604165.add(12);
        genreIds604165.add(878);
        res604165.setGenreIds(genreIds604165);
        ContentResponse res505600 = new ContentResponse("Booksmart", "2019-05-24", "Two academic teenage superstars realize, on the eve of their high school graduation, that they should have worked less and played more. Determined to never fall short of their peers, the girls set out on a mission to cram four years of fun into one night.", "505600", "/2aSxRDmisJP90H3S0aocyuQIe4z.jpg", "/wcAqndL2MkIjPrCrYeuE794weNE.jpg", 7.2f, " movie");
        List<Integer> genreIds505600 = new ArrayList<>();
        contents.add(res505600);
        genreIds505600.add(35);
        genreIds505600.add(18);
        res505600.setGenreIds(genreIds505600);

        return contents;
    }

    public static List<Content> generateDummyTvs() {
        List<Content> contents = new ArrayList<>();
        Content con1412 = new Content("Arrow", "2012-10-10", "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.", "1412", "/mo0FP1GxOFZT4UDde7RFDz5APXF.jpg", "/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg", 5.8f, " tv");
        ArrayList<Integer> genreIds1412 = new ArrayList<>();
        contents.add(con1412);
        genreIds1412.add(80);
        genreIds1412.add(18);
        genreIds1412.add(9648);
        genreIds1412.add(10759);
        con1412.setGenreIds(genreIds1412);
        Content con62286 = new Content("Fear the Walking Dead", "2015-08-23", "What did the world look like as it was transforming into the horrifying apocalypse depicted in \"The Walking Dead\"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.", "62286", "/lZMb3R3e5vqukPbeDMeyYGf2ZNG.jpg", "/7r4FieFH6Eh6S55hi8c9LOiFENg.jpg", 6.3f, " tv");
        ArrayList<Integer> genreIds62286 = new ArrayList<>();
        contents.add(con62286);
        genreIds62286.add(18);
        genreIds62286.add(27);
        con62286.setGenreIds(genreIds62286);
        Content con1622 = new Content("Supernatural", "2005-09-13", "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ", "1622", "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg", "/o9OKe3M06QMLOzTl3l6GStYtnE9.jpg", 7.4f, " tv");
        ArrayList<Integer> genreIds1622 = new ArrayList<>();
        contents.add(con1622);
        genreIds1622.add(18);
        genreIds1622.add(9648);
        genreIds1622.add(10765);
        con1622.setGenreIds(genreIds1622);
        Content con60735 = new Content("The Flash", "2014-10-07", "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.", "60735", "/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg", "/6ZdQTBy20HzWudZthAV7NkZWfIb.jpg", 6.7f, " tv");
        ArrayList<Integer> genreIds60735 = new ArrayList<>();
        contents.add(con60735);
        genreIds60735.add(18);
        genreIds60735.add(10765);
        con60735.setGenreIds(genreIds60735);
        Content con456 = new Content("The Simpsons", "1989-12-17", "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.", "456", "/yTZQkSsxUFJZJe67IenRM0AEklc.jpg", "/f5uNbUC76oowt5mt5J9QlqrIYQ6.jpg", 7.1f, " tv");
        ArrayList<Integer> genreIds456 = new ArrayList<>();
        contents.add(con456);
        genreIds456.add(16);
        genreIds456.add(35);
        con456.setGenreIds(genreIds456);
        Content con1434 = new Content("Family Guy", "1999-01-31", "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.", "1434", "/gBGUL1UTUNmdRQT8gA1LUV4yg39.jpg", "/pH38r4TWTqq7Mcs6XAlwgzNUeJe.jpg", 6.5f, " tv");
        ArrayList<Integer> genreIds1434 = new ArrayList<>();
        contents.add(con1434);
        genreIds1434.add(16);
        genreIds1434.add(35);
        con1434.setGenreIds(genreIds1434);
        Content con2734 = new Content("Law & Order: Special Victims Unit", "1999-09-20", "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.", "2734", "/6t6r1VGQTTQecN4V0sZeqsmdU9g.jpg", "/cD9PxbrdWYgL7MUpD9eOYuiSe2P.jpg", 6.4f, " tv");
        ArrayList<Integer> genreIds2734 = new ArrayList<>();
        contents.add(con2734);
        genreIds2734.add(80);
        genreIds2734.add(18);
        con2734.setGenreIds(genreIds2734);
        Content con46298 = new Content("Hunter x Hunter", "2011-10-02", "Twelve-year-old Gon Freecss one day discovers that the father he had always been told was dead was alive and well. His Father, Ging, is a Hunter—a member of society's elite with a license to go anywhere or do almost anything. Gon, determined to follow in his father's footsteps, decides to take the Hunter Examination and eventually find his father to prove himself as a Hunter in his own right. But on the way, he learns that there is more to becoming a Hunter than previously thought, and the challenges that he must face are considered the toughest in the world.", "46298", "/yWBcBIO9OrF3E85C5Arols6QNnG.jpg", "/ye4oayd3csx8psElvvQPdO2fgdD.jpg", 8.3f, " tv");
        ArrayList<Integer> genreIds46298 = new ArrayList<>();
        contents.add(con46298);
        genreIds46298.add(16);
        genreIds46298.add(35);
        genreIds46298.add(10759);
        con46298.setGenreIds(genreIds46298);
        Content con1396 = new Content("Breaking Bad", "2008-01-20", "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.", "1396", "/1yeVJox3rjo2jBKrrihIMj7uoS9.jpg", "/hbgPoI0GBrXJfGjYNV2fMQU0xou.jpg", 8.4f, " tv");
        ArrayList<Integer> genreIds1396 = new ArrayList<>();
        contents.add(con1396);
        genreIds1396.add(18);
        con1396.setGenreIds(genreIds1396);
        Content con17610 = new Content("NCIS: Los Angeles", "2009-09-22", "The exploits of the Los Angeles–based Office of Special Projects (OSP), an elite division of the Naval Criminal Investigative Service that specializes in undercover assignments.", "17610", "/p0doUtM8RhXcAwHs6VmMZMQKpai.jpg", "/j4ltPl0cHMd16UO80vbxFx1Td1w.jpg", 6.8f, " tv");
        ArrayList<Integer> genreIds17610 = new ArrayList<>();
        contents.add(con17610);
        genreIds17610.add(80);
        genreIds17610.add(18);
        genreIds17610.add(9648);
        genreIds17610.add(10759);
        con17610.setGenreIds(genreIds17610);
        Content con89247 = new Content("Batwoman", "2019-10-06", "Armed with a great passion for social justice and with a great facility to always say what she thinks, Kate Kane is known in the streets of Gotham as Batwoman, a lesbian highly trained to fight crime that resurfaces in the city. However, before becoming a savior, she must fight the demons that prevent her from being the symbol of the hope of a corrupt city.", "89247", "/jnaimWkIVSD9IInmZPyLYarSvvc.jpg", "/spc5mNkW2daK1ob7Z7jqNkSlKS2.jpg", 6.2f, " tv");
        ArrayList<Integer> genreIds89247 = new ArrayList<>();
        contents.add(con89247);
        genreIds89247.add(10759);
        genreIds89247.add(10765);
        con89247.setGenreIds(genreIds89247);
        Content con1416 = new Content("Grey's Anatomy", "2005-03-27", "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.", "1416", "/jnsvc7gCKocXnrTXF6p03cICTWb.jpg", "/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg", 6.4f, " tv");
        ArrayList<Integer> genreIds1416 = new ArrayList<>();
        contents.add(con1416);
        genreIds1416.add(18);
        con1416.setGenreIds(genreIds1416);
        Content con69050 = new Content("Riverdale", "2017-01-26", "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.", "69050", "/4X7o1ssOEvp4BFLim1AZmPNcYbU.jpg", "/2IUpoKSP64r6rp2vBo0Fdk8a1UU.jpg", 7.2f, " tv");
        ArrayList<Integer> genreIds69050 = new ArrayList<>();
        contents.add(con69050);
        genreIds69050.add(18);
        genreIds69050.add(9648);
        con69050.setGenreIds(genreIds69050);
        Content con60708 = new Content("Gotham", "2014-09-22", "Before there was Batman, there was GOTHAM. Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker? ", "60708", "/4XddcRDtnNjYmLRMYpbrhFxsbuq.jpg", "/mKBP1OCgCG0jw8DwVYlnYqVILtc.jpg", 6.9f, " tv");
        ArrayList<Integer> genreIds60708 = new ArrayList<>();
        contents.add(con60708);
        genreIds60708.add(80);
        genreIds60708.add(18);
        genreIds60708.add(14);
        con60708.setGenreIds(genreIds60708);
        Content con60625 = new Content("Rick and Morty", "2013-12-02", "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.", "60625", "/qJdfO3ahgAMf2rcmhoqngjBBZW1.jpg", "/mzzHr6g1yvZ05Mc7hNj3tUdy2bM.jpg", 8.5f, " tv");
        ArrayList<Integer> genreIds60625 = new ArrayList<>();
        contents.add(con60625);
        genreIds60625.add(16);
        genreIds60625.add(35);
        genreIds60625.add(10759);
        genreIds60625.add(10765);
        con60625.setGenreIds(genreIds60625);
        Content con46952 = new Content("The Blacklist", "2013-09-23", "Raymond \"Red\" Reddington, one of the FBI's most wanted fugitives, surrenders in person at FBI Headquarters in Washington, D.C. He claims that he and the FBI have the same interests: bringing down dangerous criminals and terrorists. In the last two decades, he's made a list of criminals and terrorists that matter the most but the FBI cannot find because it does not know they exist. Reddington calls this \"The Blacklist\". Reddington will co-operate, but insists that he will speak only to Elizabeth Keen, a rookie FBI profiler.", "46952", "/bgbQCW4fE9b6wSOSC6Fb4FfVzsW.jpg", "/fHwiAqIKragaCbNJo9Qs4lrccIN.jpg", 6.9f, " tv");
        ArrayList<Integer> genreIds46952 = new ArrayList<>();
        contents.add(con46952);
        genreIds46952.add(80);
        genreIds46952.add(18);
        genreIds46952.add(9648);
        con46952.setGenreIds(genreIds46952);
        Content con2190 = new Content("South Park", "1997-08-13", "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.", "2190", "/v9zc0cZpy5aPSfAy6Tgb6I1zWgV.jpg", "/mSDKNVvDfitFE6Fb6fSSl5DQmgS.jpg", 7.8f, " tv");
        ArrayList<Integer> genreIds2190 = new ArrayList<>();
        contents.add(con2190);
        genreIds2190.add(16);
        genreIds2190.add(35);
        con2190.setGenreIds(genreIds2190);
        Content con62688 = new Content("Supergirl", "2015-10-26", "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.", "62688", "/4ka8vAzAFUZFKxWyfGfwVcSXuZo.jpg", "/3x1lVyxtsLKsZyR2E3qRe1EAXG4.jpg", 5.9f, " tv");
        ArrayList<Integer> genreIds62688 = new ArrayList<>();
        contents.add(con62688);
        genreIds62688.add(28);
        genreIds62688.add(12);
        genreIds62688.add(18);
        genreIds62688.add(878);
        con62688.setGenreIds(genreIds62688);
        Content con91299 = new Content("Assassins Pride", "2019-10-10", "In the world only the aristocrats have the power to fight the monster - mana. Even though Melida Angel was born in an aristocracy and studies at an academy developing mana users, she has no mana. To find her talent for mana, Kufa Vampir was sent to be her tutor but at the same time, he was ordered to assassinate her if she has no talent for mana. He makes a cruel decision to assassinate her because he thinks that it is a wasted effort that people who have not any mana are working hard in this world... However, he asks her, \"Do you want to try to entrust your life to me?\" He is not as an assassin nor a tutor. He is someone betting on his pride as an assassin tutor, to show the world what Melida is capable of!", "91299", "/oR5GH0hdYClkRgaTTu3eJbtjyyY.jpg", "/3utOjRBbcyuvlETJcGCngFfVNAE.jpg", 5.2f, " tv");
        ArrayList<Integer> genreIds91299 = new ArrayList<>();
        contents.add(con91299);
        genreIds91299.add(80);
        genreIds91299.add(18);
        genreIds91299.add(10759);
        con91299.setGenreIds(genreIds91299);
        Content con60573 = new Content("Silicon Valley", "2014-04-06", "In the high-tech gold rush of modern Silicon Valley, the people most qualified to succeed are the least capable of handling success. Partially inspired by Mike Judge’s own experiences as a Silicon Valley engineer in the late ‘80s, Silicon Valley is an American sitcom that centers around six programmers who are living together and trying to make it big in the Silicon Valley.", "60573", "/a154rIMzbTyefodNp4NY8qjOEfC.jpg", "/8vk5R31KG5UQTAwTVEBxn65NSB.jpg", 8.0f, " tv");
        ArrayList<Integer> genreIds60573 = new ArrayList<>();
        contents.add(con60573);
        genreIds60573.add(35);
        con60573.setGenreIds(genreIds60573);

        return contents;
    }

    public static List<ContentResponse> generateRemoteDummyTvs() {
        List<ContentResponse> contents = new ArrayList<>();

        ContentResponse res1412 = new ContentResponse("Arrow", "2012-10-10", "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.", "1412", "/mo0FP1GxOFZT4UDde7RFDz5APXF.jpg", "/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg", 5.8f, " tv");
        List<Integer> genreIds1412 = new ArrayList<>();
        contents.add(res1412);
        genreIds1412.add(80);
        genreIds1412.add(18);
        genreIds1412.add(9648);
        genreIds1412.add(10759);
        res1412.setGenreIds(genreIds1412);
        ContentResponse res62286 = new ContentResponse("Fear the Walking Dead", "2015-08-23", "What did the world look like as it was transforming into the horrifying apocalypse depicted in \"The Walking Dead\"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.", "62286", "/lZMb3R3e5vqukPbeDMeyYGf2ZNG.jpg", "/7r4FieFH6Eh6S55hi8c9LOiFENg.jpg", 6.3f, " tv");
        List<Integer> genreIds62286 = new ArrayList<>();
        contents.add(res62286);
        genreIds62286.add(18);
        genreIds62286.add(27);
        res62286.setGenreIds(genreIds62286);
        ContentResponse res1622 = new ContentResponse("Supernatural", "2005-09-13", "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ", "1622", "/KoYWXbnYuS3b0GyQPkbuexlVK9.jpg", "/o9OKe3M06QMLOzTl3l6GStYtnE9.jpg", 7.4f, " tv");
        List<Integer> genreIds1622 = new ArrayList<>();
        contents.add(res1622);
        genreIds1622.add(18);
        genreIds1622.add(9648);
        genreIds1622.add(10765);
        res1622.setGenreIds(genreIds1622);
        ContentResponse res60735 = new ContentResponse("The Flash", "2014-10-07", "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won't be long before the world learns what Barry Allen has become...The Flash.", "60735", "/wHa6KOJAoNTFLFtp7wguUJKSnju.jpg", "/6ZdQTBy20HzWudZthAV7NkZWfIb.jpg", 6.7f, " tv");
        List<Integer> genreIds60735 = new ArrayList<>();
        contents.add(res60735);
        genreIds60735.add(18);
        genreIds60735.add(10765);
        res60735.setGenreIds(genreIds60735);
        ContentResponse res456 = new ContentResponse("The Simpsons", "1989-12-17", "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.", "456", "/yTZQkSsxUFJZJe67IenRM0AEklc.jpg", "/f5uNbUC76oowt5mt5J9QlqrIYQ6.jpg", 7.1f, " tv");
        List<Integer> genreIds456 = new ArrayList<>();
        contents.add(res456);
        genreIds456.add(16);
        genreIds456.add(35);
        res456.setGenreIds(genreIds456);
        ContentResponse res1434 = new ContentResponse("Family Guy", "1999-01-31", "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.", "1434", "/gBGUL1UTUNmdRQT8gA1LUV4yg39.jpg", "/pH38r4TWTqq7Mcs6XAlwgzNUeJe.jpg", 6.5f, " tv");
        List<Integer> genreIds1434 = new ArrayList<>();
        contents.add(res1434);
        genreIds1434.add(16);
        genreIds1434.add(35);
        res1434.setGenreIds(genreIds1434);
        ContentResponse res2734 = new ContentResponse("Law & Order: Special Victims Unit", "1999-09-20", "In the criminal justice system, sexually-based offenses are considered especially heinous. In New York City, the dedicated detectives who investigate these vicious felonies are members of an elite squad known as the Special Victims Unit. These are their stories.", "2734", "/6t6r1VGQTTQecN4V0sZeqsmdU9g.jpg", "/cD9PxbrdWYgL7MUpD9eOYuiSe2P.jpg", 6.4f, " tv");
        List<Integer> genreIds2734 = new ArrayList<>();
        contents.add(res2734);
        genreIds2734.add(80);
        genreIds2734.add(18);
        res2734.setGenreIds(genreIds2734);
        ContentResponse res46298 = new ContentResponse("Hunter x Hunter", "2011-10-02", "Twelve-year-old Gon Freecss one day discovers that the father he had always been told was dead was alive and well. His Father, Ging, is a Hunter—a member of society's elite with a license to go anywhere or do almost anything. Gon, determined to follow in his father's footsteps, decides to take the Hunter Examination and eventually find his father to prove himself as a Hunter in his own right. But on the way, he learns that there is more to becoming a Hunter than previously thought, and the challenges that he must face are considered the toughest in the world.", "46298", "/yWBcBIO9OrF3E85C5Arols6QNnG.jpg", "/ye4oayd3csx8psElvvQPdO2fgdD.jpg", 8.3f, " tv");
        List<Integer> genreIds46298 = new ArrayList<>();
        contents.add(res46298);
        genreIds46298.add(16);
        genreIds46298.add(35);
        genreIds46298.add(10759);
        res46298.setGenreIds(genreIds46298);
        ContentResponse res1396 = new ContentResponse("Breaking Bad", "2008-01-20", "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.", "1396", "/1yeVJox3rjo2jBKrrihIMj7uoS9.jpg", "/hbgPoI0GBrXJfGjYNV2fMQU0xou.jpg", 8.4f, " tv");
        List<Integer> genreIds1396 = new ArrayList<>();
        contents.add(res1396);
        genreIds1396.add(18);
        res1396.setGenreIds(genreIds1396);
        ContentResponse res17610 = new ContentResponse("NCIS: Los Angeles", "2009-09-22", "The exploits of the Los Angeles–based Office of Special Projects (OSP), an elite division of the Naval Criminal Investigative Service that specializes in undercover assignments.", "17610", "/p0doUtM8RhXcAwHs6VmMZMQKpai.jpg", "/j4ltPl0cHMd16UO80vbxFx1Td1w.jpg", 6.8f, " tv");
        List<Integer> genreIds17610 = new ArrayList<>();
        contents.add(res17610);
        genreIds17610.add(80);
        genreIds17610.add(18);
        genreIds17610.add(9648);
        genreIds17610.add(10759);
        res17610.setGenreIds(genreIds17610);
        ContentResponse res89247 = new ContentResponse("Batwoman", "2019-10-06", "Armed with a great passion for social justice and with a great facility to always say what she thinks, Kate Kane is known in the streets of Gotham as Batwoman, a lesbian highly trained to fight crime that resurfaces in the city. However, before becoming a savior, she must fight the demons that prevent her from being the symbol of the hope of a corrupt city.", "89247", "/jnaimWkIVSD9IInmZPyLYarSvvc.jpg", "/spc5mNkW2daK1ob7Z7jqNkSlKS2.jpg", 6.2f, " tv");
        List<Integer> genreIds89247 = new ArrayList<>();
        contents.add(res89247);
        genreIds89247.add(10759);
        genreIds89247.add(10765);
        res89247.setGenreIds(genreIds89247);
        ContentResponse res1416 = new ContentResponse("Grey's Anatomy", "2005-03-27", "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.", "1416", "/jnsvc7gCKocXnrTXF6p03cICTWb.jpg", "/edmk8xjGBsYVIf4QtLY9WMaMcXZ.jpg", 6.4f, " tv");
        List<Integer> genreIds1416 = new ArrayList<>();
        contents.add(res1416);
        genreIds1416.add(18);
        res1416.setGenreIds(genreIds1416);
        ContentResponse res69050 = new ContentResponse("Riverdale", "2017-01-26", "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.", "69050", "/4X7o1ssOEvp4BFLim1AZmPNcYbU.jpg", "/2IUpoKSP64r6rp2vBo0Fdk8a1UU.jpg", 7.2f, " tv");
        List<Integer> genreIds69050 = new ArrayList<>();
        contents.add(res69050);
        genreIds69050.add(18);
        genreIds69050.add(9648);
        res69050.setGenreIds(genreIds69050);
        ContentResponse res60708 = new ContentResponse("Gotham", "2014-09-22", "Before there was Batman, there was GOTHAM. Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker? ", "60708", "/4XddcRDtnNjYmLRMYpbrhFxsbuq.jpg", "/mKBP1OCgCG0jw8DwVYlnYqVILtc.jpg", 6.9f, " tv");
        List<Integer> genreIds60708 = new ArrayList<>();
        contents.add(res60708);
        genreIds60708.add(80);
        genreIds60708.add(18);
        genreIds60708.add(14);
        res60708.setGenreIds(genreIds60708);
        ContentResponse res60625 = new ContentResponse("Rick and Morty", "2013-12-02", "Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.", "60625", "/qJdfO3ahgAMf2rcmhoqngjBBZW1.jpg", "/mzzHr6g1yvZ05Mc7hNj3tUdy2bM.jpg", 8.5f, " tv");
        List<Integer> genreIds60625 = new ArrayList<>();
        contents.add(res60625);
        genreIds60625.add(16);
        genreIds60625.add(35);
        genreIds60625.add(10759);
        genreIds60625.add(10765);
        res60625.setGenreIds(genreIds60625);
        ContentResponse res46952 = new ContentResponse("The Blacklist", "2013-09-23", "Raymond \"Red\" Reddington, one of the FBI's most wanted fugitives, surrenders in person at FBI Headquarters in Washington, D.C. He claims that he and the FBI have the same interests: bringing down dangerous criminals and terrorists. In the last two decades, he's made a list of criminals and terrorists that matter the most but the FBI cannot find because it does not know they exist. Reddington calls this \"The Blacklist\". Reddington will co-operate, but insists that he will speak only to Elizabeth Keen, a rookie FBI profiler.", "46952", "/bgbQCW4fE9b6wSOSC6Fb4FfVzsW.jpg", "/fHwiAqIKragaCbNJo9Qs4lrccIN.jpg", 6.9f, " tv");
        List<Integer> genreIds46952 = new ArrayList<>();
        contents.add(res46952);
        genreIds46952.add(80);
        genreIds46952.add(18);
        genreIds46952.add(9648);
        res46952.setGenreIds(genreIds46952);
        ContentResponse res2190 = new ContentResponse("South Park", "1997-08-13", "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.", "2190", "/v9zc0cZpy5aPSfAy6Tgb6I1zWgV.jpg", "/mSDKNVvDfitFE6Fb6fSSl5DQmgS.jpg", 7.8f, " tv");
        List<Integer> genreIds2190 = new ArrayList<>();
        contents.add(res2190);
        genreIds2190.add(16);
        genreIds2190.add(35);
        res2190.setGenreIds(genreIds2190);
        ContentResponse res62688 = new ContentResponse("Supergirl", "2015-10-26", "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.", "62688", "/4ka8vAzAFUZFKxWyfGfwVcSXuZo.jpg", "/3x1lVyxtsLKsZyR2E3qRe1EAXG4.jpg", 5.9f, " tv");
        List<Integer> genreIds62688 = new ArrayList<>();
        contents.add(res62688);
        genreIds62688.add(28);
        genreIds62688.add(12);
        genreIds62688.add(18);
        genreIds62688.add(878);
        res62688.setGenreIds(genreIds62688);
        ContentResponse res91299 = new ContentResponse("Assassins Pride", "2019-10-10", "In the world only the aristocrats have the power to fight the monster - mana. Even though Melida Angel was born in an aristocracy and studies at an academy developing mana users, she has no mana. To find her talent for mana, Kufa Vampir was sent to be her tutor but at the same time, he was ordered to assassinate her if she has no talent for mana. He makes a cruel decision to assassinate her because he thinks that it is a wasted effort that people who have not any mana are working hard in this world... However, he asks her, \"Do you want to try to entrust your life to me?\" He is not as an assassin nor a tutor. He is someone betting on his pride as an assassin tutor, to show the world what Melida is capable of!", "91299", "/oR5GH0hdYClkRgaTTu3eJbtjyyY.jpg", "/3utOjRBbcyuvlETJcGCngFfVNAE.jpg", 5.2f, " tv");
        List<Integer> genreIds91299 = new ArrayList<>();
        contents.add(res91299);
        genreIds91299.add(80);
        genreIds91299.add(18);
        genreIds91299.add(10759);
        res91299.setGenreIds(genreIds91299);
        ContentResponse res60573 = new ContentResponse("Silicon Valley", "2014-04-06", "In the high-tech gold rush of modern Silicon Valley, the people most qualified to succeed are the least capable of handling success. Partially inspired by Mike Judge’s own experiences as a Silicon Valley engineer in the late ‘80s, Silicon Valley is an American sitcom that centers around six programmers who are living together and trying to make it big in the Silicon Valley.", "60573", "/a154rIMzbTyefodNp4NY8qjOEfC.jpg", "/8vk5R31KG5UQTAwTVEBxn65NSB.jpg", 8.0f, " tv");
        List<Integer> genreIds60573 = new ArrayList<>();
        contents.add(res60573);
        genreIds60573.add(35);
        res60573.setGenreIds(genreIds60573);

        return contents;
    }
}
